### ISSUE TITLE
Alteração do body do login

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio-api#1]
Creio que alterar o "username_or_email" por dois atributos, um "username" e um "email" (e pode ser enviado qualquer um) manteria a consistência no objeto.

```
{
  "user": {
    "username_or_email": "test123",
    "password": "hunter1"
  }
}
```

para 
```
{
  "user": {
    "username": "test123",
    "email" : "test@example.com",
    "password": "hunter1"
  }
}
```

**Comment by andreihod** [comment]
[Esquece essa merda aí, porra](https://youtu.be/-NGdPQ7KIxM?t=9)
