### ISSUE TITLE
Colocar só email

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio-api#2]
Não faz sentido ter um campo de usuário se a intenção é manter interno. Nomes de usuário são um campo desnecessário a não ser que sejam para redes sociais.

**Comment by andreihod** [comment]
A intenção é usar como:

1. Login: pois é menor que o e-mail
2. Criar um perfil compartilhável futuramente (i.e. "/u/andrei")

Sendo assim, tudo bem ter o username.
