### ISSUE TITLE
liberar Access-Control-Allow-Origin para OPTIONS

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio-api#3]
OPTIONS http://www.getcryptofolio.com:4001/api/auth/signup 

XMLHttpRequest cannot load http://www.getcryptofolio.com:4001/api/auth/signup. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.

**Comment by andreihod** [comment]
HABILITAREI-LHO-VOS

**Comment by naurojunior** [comment]
Meu presidento!

**Comment by andreihod** [comment]
Habilitei o CORS, testa lá fazendo o favor. Fiz também:

1. Porta 80 habilitada e apontando pro Phoenix.
2. HTTPS habilitado, e obrigatório.

TO-DO: bloquear a porta 4001 de acesso externo xD

**Comment by andreihod** [comment]
Arrumei aquele problema que só acessava pelo "www", agora funciona com e sem.
O endereço agora então ficou https://getcryptofolio.com

**Comment by naurojunior** [comment]
Só da uma olhada, fui testar aqui com senha menor que 5 dígitos, ele avisou o erro. Alterei a senha para 7 dígitos e ele avisou que o username já estava em uso.

**Comment by naurojunior** [comment]
Fiz uns testes, tá funcionando SHOW. Mas parece que mesmo quando ele gera um erro, ele acaba salvando no banco.

**Comment by naurojunior** [comment]
Tá respondendo com Internal Server Error agora :|

**Comment by andreihod** [comment]
@naurojunior onde exatamente o erro?

**Comment by naurojunior** [comment]
Esquece, acho que era caca minha
