### ISSUE TITLE
Desenvolver endpoint de Assets

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio-api#5]

**Comment by andreihod** [comment]
Fiz, ta lá, a princípio está funcionando, mas vê se tu encontra algum problema: `/assets`

POST e PUT com esses atributos:
`{
	"asset": {
		"mybalance": 0.1,
		"coin_id": 1,
		"exchange_id": 1
	}
}`

**Comment by naurojunior** [comment]
Depois passa o link do logo novo. Meu cachorro tá pedindo links
