### ISSUE TITLE
Desenvolver endpoint de SupportedCoins

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio-api#6]

**Comment by andreihod** [comment]
GET /coins/ e /coins/:id

**Comment by andreihod** [comment]
mudei o /exchange pra NÃO usar mais o "data" também HE HE

**Comment by naurojunior** [comment]
Breaking Change total, e o cara me bota em produção assim, sem a homologação de nossos advogados. tsc, tsc, tsc :/

P.S: Aquele update que a gente ama

**Comment by andreihod** [comment]
MOVE FAST AND BREAK THINGS

**Comment by andreihod** [comment]
fiz agora `/coins/:id/exchanges`, que pega todas as exchanges/markets que tem essa moeda

**Comment by naurojunior** [comment]
update do client tá no forno assando

**Comment by naurojunior** [comment]
Tem como no /coins/;id/exchanges retornar algo nesse estilo?

```
{ 
  "coin": { 
      //dados da moeda
   },
 [{"exchange":{"price":null,"name":"Poloniex","market":{"currencyTo":"USD","currencyFrom":"BTC"},"id":1}},{"exchange":{"price":null,"name":"Poloniex","market":{"currencyTo":"EUR","currencyFrom":"BTC"},"id":2}},{"exchange":{"price":null,"name":"Poloniex","market":{"currencyTo":"ETH","currencyFrom":"BTC"},"id":3}}]
}
```

Porque webservice "coin" deve trazer a moeda com exchanges.

**Comment by andreihod** [comment]
Faz sentido, vou fazer 😉

________________________________
De: Nauro da Silva Júnior <notifications@github.com>
Enviado: quarta-feira, 2 de agosto de 2017 20:50:42
Para: andreihod/cryptofolio-api
Cc: Andrei Hodecker; Assign
Assunto: Re: [andreihod/cryptofolio-api] Desenvolver endpoint de SupportedCoins (#6)


Tem como no /coins/;id/exchanges retornar algo nesse estilo?

{
  "coin": {
      //dados da moeda
   },
 [{"exchange":{"price":null,"name":"Poloniex","market":{"currencyTo":"USD","currencyFrom":"BTC"},"id":1}},{"exchange":{"price":null,"name":"Poloniex","market":{"currencyTo":"EUR","currencyFrom":"BTC"},"id":2}},{"exchange":{"price":null,"name":"Poloniex","market":{"currencyTo":"ETH","currencyFrom":"BTC"},"id":3}}]
}


Porque webservice "coin" deve trazer a moeda com exchanges.
