### ISSUE TITLE
Corrigir OrderBy

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio-api#7]
Quando eu salvo uma edição e requisito a atualização, ele joga o que foi atualizado para o final.

Ordena por id descendente

**Comment by andreihod** [comment]
Feito! Na verdade fiz ordenar por data de inserção (o que dá no mesmo).
Aproveitei e coloquei os campos "inserted_at" e "updated_at" p/ os assets.

**Comment by naurojunior** [comment]
Não é pretérito, mas é mais-que-perfeito
